import "/assets/libs/animate/style.scss";
import "/assets/libs/fancybox/style.css";
import "/assets/libs/remodal/remodal-default-theme.min.css";
import "/assets/libs/remodal/remodal.min.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import "/assets/css/fonts.css";
import "/assets/css/animate.css";
import "/assets/css/vars.css";
import "/assets/css/general.css";
import "/assets/scss/global.scss";
import "/assets/scss/layout.scss";
import "/assets/scss/index.scss";
import "/assets/scss/dark-theme.scss";
import "/assets/libs/lidrekon/style.scss";
import "/assets/scss/media.scss";
import "/assets/scss/max1200.scss";
import "/assets/scss/max991.scss";
import "/assets/scss/max768.scss";
import "/assets/scss/max576.scss";
import "/assets/scss/max360.scss";

import "/assets/js/index.js";
import "/assets/js/ajax_handler.js";
// import "/assets/libs/lidrekon/script.min.js";
